name: Deploy with Password

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Project
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: |
        npm install
        npm run build

    - name: Upload via SCP
      uses: docker://ghcr.io/appleboy/scp-action:v0.4.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "build/*"
        target: ${{ secrets.SERVER_TARGET }}

    - name: Restart Service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          docker exec nginx-container nginx -s reload
